export const isoToHC = (iso) => {
  switch(iso) {
    case 'RU-ALT':
      return 'ru-al';
    case 'RU-AMU':
        return 'ru-am';
    case 'RU-ARK':
        return 'ru-ar';
    case 'RU-AST':
        return 'ru-as';
    case 'RU-BEL':
        return 'ru-be';
    case 'RU-BRY':
        return 'ru-br';
    case 'RU-CHE':
        return 'ru-ch';
    case 'RU-CHU':
        return 'ru-ck';
    case 'RU-DA':
        return 'ru-da';
    case 'RU-IN':
        return 'ru-in';
    case 'RU-IRK':
        return 'ru-ir';
    case 'RU-IVA':
        return 'ru-iv';
    case 'RU-KAM':
        return 'ru-ka';
    case 'RU-KB':
        return 'ru-kb';
    case 'RU-KC':
        return 'ru-kc';
    case 'RU-KDA':
        return 'ru-kl';
    case 'RU-KEM':
        return 'ru-km';
    case 'RU-KGD':
        return 'ru-kg';
    case 'RU-KGN':
        return 'ru-kn';
    case 'RU-KHA':
        return 'ru-kh';
    case 'RU-KHM':
        return 'ru-kk';
    case 'RU-KIR':
        return 'ru-ki';
    case 'RU-KK':
        return 'ru-kr';
    case 'RU-KL':
        return 'ru-ko';
    case 'RU-KLU':
        return 'ru-kl';
    case 'RU-KO':
        return 'ru-ko';
    case 'RU-KOS':
        return 'ru-ks';
    case 'RU-KR':
        return 'ru-kr';
    case 'RU-KRS':
        return 'ru-kz';
    case 'RU-KYA':
        return 'ru-ky';
    case 'RU-LEN':
        return 'ru-le';
    case 'RU-LIP':
        return 'ru-li';
    case 'RU-MAG':
        return 'ru-ma';
    case 'RU-ME':
        return 'ru-me';
    case 'RU-MO':
        return 'ru-mo';
    case 'RU-MOS':
        return 'ru-2510';
    case 'RU-MOW':
        return 'ru-ms';
    case 'RU-MUR':
        return 'ru-mm';
    case 'RU-NEN':
        return 'ru-ne';
    case 'RU-NGR':
        return 'ru-nv';
    case 'RU-NIZ':
        return 'ru-nz';
    case 'RU-NVS':
        return 'ru-nv';
    case 'RU-OMS':
        return 'ru-om';
    case 'RU-ORE':
        return 'ru-or';
    case 'RU-ORL':
        return 'ru-ol';
    case 'RU-PER':
        return 'ru-pe';
    case 'RU-PNZ':
        return 'ru-pz';
    case 'RU-PRI':
        return 'ru-pr';
    case 'RU-PSK':
        return 'ru-ps';
    case 'RU-ROS':
        return 'ru-ro';
    case 'RU-RYA':
        return 'ru-ry';
    case 'RU-SA':
        return 'ru-sk';
    case 'RU-SAK':
        return 'ru-sl';
    case 'RU-SAM':
        return 'ru-sm';
    case 'RU-SAR':
        return 'ru-sr';
    case 'RU-SE':
        return 'ru-se';
    case 'RU-SMO':
        return 'ru-sm';
    case 'RU-SPE':
        return 'ru-sp';
    case 'RU-STA':
        return 'ru-st';
    case 'RU-SVE':
        return 'ru-sv';
    case 'RU-TA':
        return 'ru-ta';
    case 'RU-TAM':
        return 'ru-tm';
    case 'RU-TOM':
        return 'ru-to';
    case 'RU-TUL':
        return 'ru-tl';
    case 'RU-TVE':
        return 'ru-tv';
    case 'RU-TY':
        return 'ru-ty';
    case 'RU-TYU':
        return 'ru-ty';
    case 'RU-UD':
        return 'ru-ud';
    case 'RU-ULY':
        return 'ru-ul';
    case 'RU-VGG':
        return 'ru-vl';
    case 'RU-VLA':
        return 'ru-vl';
    case 'RU-VLG':
        return 'ru-vl';
    case 'RU-VOR':
        return 'ru-vo';
    case 'RU-YAN':
        return 'ru-ya';
    case 'RU-YAR':
        return 'ru-ya';
    case 'RU-YEV':
        return 'ru-yv';
    case 'RU-ZAB':
        return 'ru-zb';
    case 'RU-ZAP':
        return 'ru-zp';
    case 'RU-ZAR':
        return 'ru-zr';
    case 'RU-CE':
        return 'ru-ce';
        
  }
};



 ['RU-ALT', 'RU-AMU', 'RU-ARK', 'RU-AST', 'RU-BEL', 'RU-BRY', 'RU-VLA', 'RU-VGG', 'RU-VLG', 'RU-VOR', 'RU-YEV', 'RU-ZAB', 'RU-IVA', 'RU-IRK', 'RU-KB', 'RU-KGD', 'RU-KLU', 'RU-KAM', 'RU-KC', 'RU-KEM', 'RU-KIR', 'RU-KOS', 'RU-KDA', 'RU-KYA', 'RU-KGN', 'RU-KRS', 'RU-LEN', 'RU-LIP', 'RU-MAG', 'RU-MOW', 'RU-MOS', 'RU-MUR', 'RU-NIZ', 'RU-NGR', 'RU-NVS', 'RU-OMS', 'RU-ORE', 'RU-ORL', 'RU-PNZ', 'RU-PER', 'RU-PRI', 'RU-PSK', 'RU-AD', 'RU-AL', 'RU-BA', 'RU-BU', 'RU-DA', 'RU-IN', 'RU-KL', 'RU-KR', 'RU-KO', 'UA-43', 'RU-ME', 'RU-MO', 'RU-SA', 'RU-SE', 'RU-TA', 'RU-TY', 'RU-KK', 'RU-ROS', 'RU-RYA', 'RU-SAM', 'RU-SPE', 'RU-SAR', 'RU-SAK', 'RU-SVE', 'UA-40', 'RU-SMO', 'RU-STA', 'RU-TAM', 'RU-TVE', 'RU-TOM', 'RU-TUL', 'RU-TYU', 'RU-UD', 'RU-ULY', 'RU-KHA', 'RU-CHE', 'RU-CE', 'RU-CU', 'RU-CHU', 'RU-YAR']